# Generated by Django 5.1.5 on 2025-02-05 05:36

import admintpa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.IntegerField()),
                ('id_mapel', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('des', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agtkelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_absensi', models.IntegerField()),
                ('id_agtkelas', models.IntegerField()),
                ('keterangan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('nama', models.CharField(max_length=100)),
                ('tmpt_lahir', models.CharField(max_length=20)),
                ('tgl_lahir', models.DateField()),
                ('jkl', models.CharField(max_length=20)),
                ('agama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=50)),
                ('notelp', models.CharField(max_length=20)),
                ('foto1', models.ImageField(upload_to=admintpa.models.upload_to)),
                ('foto2', models.ImageField(upload_to=admintpa.models.upload_to)),
                ('foto3', models.ImageField(upload_to=admintpa.models.upload_to)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
