# Generated by Django 5.1.5 on 2025-02-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintpa', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='batas',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
