# Generated by Django 5.1.5 on 2025-02-13 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintpa', '0004_kehadiran_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='batas',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
