# Generated by Django 5.1.5 on 2025-02-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintpa', '0005_alter_absensi_batas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='batas',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
