# Generated by Django 5.1.5 on 2025-02-13 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintpa', '0006_alter_absensi_batas'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='mulai',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
