# Generated by Django 5.1.5 on 2025-02-14 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintpa', '0007_absensi_mulai_alter_absensi_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='jam',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
