# Generated by Django 5.1.5 on 2025-02-14 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintpa', '0008_kehadiran_jam_alter_kehadiran_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='tanggal',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
